NAME: Pretrain_HumanML3D_3e_4 # Experiment names
ACCELERATOR: 'gpu' # Devices optioncal: “cpu”, “gpu”, “tpu”, “ipu”, “hpu”, “mps, “auto”
NUM_NODES: 1 # Number of GPU nodes for distributed training
DEVICE: [0,1,2,3] # Index of gpus eg. [0] or [0,1,2,3]

TRAIN:
  #---------------------------------
  STAGE: lm_pretrain # stage "vae" , "lm_pretrain", "lm_instruct"
  #---------------------------------
  NUM_WORKERS: 16 # Number of workers
  BATCH_SIZE: 32 # Size of batches
  END_EPOCH: 10000 # End epoch
  RESUME: '' # Resume training from this path
  PRETRAINED: '' # Preatrained model path
  PRETRAINED_VAE: /comp_robot/lushunlin/MotionGPT_chenxin/experiments/mgpt/VQVAE_HumanML3D/checkpoints/epoch=4999-v1.ckpt # Vae model path

  OPTIM:
    target: AdamW
    params:
      lr: 3e-4
      betas: [0.9, 0.99]
      weight_decay: 0.0

# Evaluating Configuration
EVAL:
  BATCH_SIZE: 32 # Evaluating Batch size
  SPLIT: test

TEST:
  CHECKPOINTS: checkpoints/MotionGPT-base/motiongpt_s3_h3d.tar
  SPLIT: test
  BATCH_SIZE: 32 # training Batch size

DATASET:
  target: mGPT.data.HumanML3D.HumanML3DDataModule
  CODE_PATH: TOKENS

METRIC:
  TYPE: ['TM2TMetrics', 'PredMetrics']

LOSS:
  LAMBDA_FEATURE: 1.0
  LAMBDA_VELOCITY: 0.5
  LAMBDA_COMMIT: 0.02
  LAMBDA_CLS: 1.0
  ABLATION:
    RECONS_LOSS: 'l1_smooth'

model:
  target: mGPT.models.mgpt.MotionGPT
  params:
    condition: 'text'
    task: 't2m'
    lm: ${lm.default}
    motion_vae: ${vq.default}

LOGGER:
  TYPE: ['tensorboard']
  VAL_EVERY_STEPS: 10
  WANDB:
    params:
      project: motiongpt
